### ISSUE TITLE
搬瓦工支持ChatGPT吗？

### ISSUE THREAD

**Issue by Arvinling** [Azranus/justmysocks#1]
这个JustMySocks梯子现在支持ChatGPT的使用吗？稳定吗?

**Comment by Azranus** [comment]
以下内容摘自官方：

好消息！从2023年4月12日起，ChatGPT已经可以使用。

Shadowsocks服务器（s1、s2）：从2023年5月3日起，您现在可以完全使用ChatGPT功能。

v2ray服务器（s3、s4、s5、s801）：您可以完全使用ChatGPT功能，但需要注意以下几点：

如果您使用代理应用程序（如v2rayN-core），则无需进行其他配置，它应该可以正常工作。

如果您使用VPN应用程序（通常在移动设备上），则可能需要在应用程序设置中启用以下设置才能使ChatGPT正常工作：
“启用流量嗅探”
“在VPN中附加HTTP代理”
“覆盖目标”

我们已经在以下应用程序中成功测试了上述设置：v2rayNG、NekoBox、SagerNet。

如果这些设置都无法正常工作，请设置以下VPN DNS条目：172.31.255.2。

[原文详情](https://justmysocks3.net/members/index.php?rp=/announcements/4/Further-improvements-to-ChatGPT-Unblocking.html)
