### ISSUE TITLE
上不了Chatgpt，以及twitter

### ISSUE THREAD

**Issue by fengjunjohnxu** [Azranus/justmysocks#7]
用的是LA500这个服务，但是一直上不了chatgpt，然后有一段时间过后twitter也上不了啦

**Comment by Azranus** [comment]
可以联系下[客服](https://justmysocks3.net/members/submitticket.php?step=2&deptid=1)，让换节点。或者直接上[HK 的chatgpt unlocked节点](https://justmysocks3.net/members/aff.php?aff=26082&pid=18&language=chinese)
